language: java
jdk:
  - openjdk8

script:
  - mvn test
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - jo.seph-fck-95@hotmail.com
    on_failure: always
